
import React from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'terms' | 'privacy';
}

export function LegalModal({ isOpen, onClose, type }: LegalModalProps) {
  const isTerms = type === 'terms';

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle>{isTerms ? 'Terms of Service' : 'Privacy Policy'}</DialogTitle>
          <DialogDescription>
            Last updated: November 25, 2025
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] pr-4">
          <div className="space-y-4 text-sm text-muted-foreground">
            {isTerms ? <TermsContent /> : <PrivacyContent />}
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}

function TermsContent() {
  return (
    <>
      <h3 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h3>
      <p>
        By accessing and using Money GPT ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.
      </p>

      <h3 className="text-lg font-semibold text-foreground">2. Description of Service</h3>
      <p>
        Money GPT provides AI-powered prompt analysis, scoring, and optimization services. We use advanced algorithms to evaluate prompts based on Idea, Cost, and Exploitability (ICE) and other proprietary metrics.
      </p>

      <h3 className="text-lg font-semibold text-foreground">3. User Accounts</h3>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.
      </p>

      <h3 className="text-lg font-semibold text-foreground">4. Payment and Subscriptions</h3>
      <p>
        Certain features of the Platform require a paid subscription. By subscribing, you agree to pay the applicable fees. Payments are processed by secure third-party providers (e.g., Stripe). Refunds are handled on a case-by-case basis.
      </p>

      <h3 className="text-lg font-semibold text-foreground">5. Intellectual Property</h3>
      <p>
        The analysis, scores, and suggestions generated by the Platform are provided for your use. However, the underlying algorithms, software, and interface remain the property of Money GPT.
      </p>

      <h3 className="text-lg font-semibold text-foreground">6. User Content</h3>
      <p>
        You retain ownership of the prompts you submit. By submitting prompts, you grant us a license to use them to provide the service and to improve our AI models (unless you are on an Enterprise plan with data exclusion).
      </p>

      <h3 className="text-lg font-semibold text-foreground">7. Limitation of Liability</h3>
      <p>
        The Platform is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Platform or reliance on its analysis.
      </p>

      <h3 className="text-lg font-semibold text-foreground">8. Changes to Terms</h3>
      <p>
        We may modify these terms at any time. Continued use of the Platform constitutes acceptance of the updated terms.
      </p>
    </>
  );
}

function PrivacyContent() {
  return (
    <>
      <h3 className="text-lg font-semibold text-foreground">1. Information We Collect</h3>
      <p>
        We collect information you provide (email, prompts) and usage data (analysis history, interaction patterns). We use cookies and similar technologies to maintain your session.
      </p>

      <h3 className="text-lg font-semibold text-foreground">2. How We Use Your Information</h3>
      <p>
        We use your data to:
        <ul className="list-disc pl-5 mt-2 space-y-1">
          <li>Provide and improve the prompt analysis service.</li>
          <li>Process payments and manage accounts.</li>
          <li>Train and refine our AI scoring models.</li>
          <li>Communicate with you about updates and offers.</li>
        </ul>
      </p>

      <h3 className="text-lg font-semibold text-foreground">3. Data Storage and Security</h3>
      <p>
        Your data is stored securely using industry-standard encryption. We use Supabase for database services and Vercel for hosting. While we strive to protect your data, no method of transmission is 100% secure.
      </p>

      <h3 className="text-lg font-semibold text-foreground">4. Data Sharing</h3>
      <p>
        We do not sell your personal data. We may share data with trusted service providers (e.g., payment processors, AI model providers like OpenAI/Google) solely for the purpose of operating the Platform.
      </p>

      <h3 className="text-lg font-semibold text-foreground">5. Your Rights</h3>
      <p>
        You can request access to, correction of, or deletion of your personal data. You can also export your analysis history at any time.
      </p>

      <h3 className="text-lg font-semibold text-foreground">6. Contact Us</h3>
      <p>
        If you have questions about this Privacy Policy, please contact us at support@moneygpt.com.
      </p>
    </>
  );
}
